safe:        true
markdown: kramdown
exclude: [node_modules, bower_components, vendor]
url: https://jhipster-dev.apps.dhccloud.com.cn/
github_repository_url: https://github.com/dystudio/dystudio-jhipster.github.io
kramdown:
  input: GFM
gems:
  - jekyll-redirect-from
  - jemoji
whitelist:
  - jekyll-redirect-from
  - jemoji
defaults:
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

theme: jekyll-theme-slate